[package]
name = "rust_tcp_sever"
version = "0.1.4"

authors = ["AmakeSasha amakesasha@gmail.com"]
description = "A simple and lightweight crate for launching and using a server"

license-file = "LICENSE.md"
repository = "https://github.com/Amakesasha/Rust-TcpSever"
readme = "README.md"

keywords = ["tcp_server", "rust_server", "rust_tcp_server", "web", "tcp"]
categories = ["web-programming::http-server", "web-programming"]


[profile.dev]
opt-level = "s"
debug = false
strip = "none"
debug-assertions = false
lto = "thin"

[profile.release]
opt-level = "s"
debug = false
strip = "none"
debug-assertions = false
lto = "thin"